version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DB_HOST=localhost
      - PORT=5000
      - DATABASE_URL=mysql://root:root@db:3306/db?schema=public
      - CRYPTO_SECRET=
      - CRYPTO_IV_SECRET=
      - CRYPTO_ALGORITHM=
      - AWS_ACCESS_KEY="AKIAXG4D774UMEY5FZGO"
      - AWS_SECRET_ACCESS_KEY="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"
      - AWS_REGION="us-east-2"
      - AWS_S3_BUCKET_NAME="no-escape-files-bucket"
    networks:
      - app
    depends_on:
      - db
    command: sh -c "npx prisma db push && npm run start"
    
volumes:
  db_data:

networks:
  app:
    driver: bridge